apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PAYMENT_URL
              value: {{ .Values.env.PAYMENT_URL | quote }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
