apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: full-cloud-devops-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME/Full-Cloud-DevOps-App
    targetRevision: HEAD
    path: helm/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
